import { addMessages } from "../i18n";

/** Strings for the AI module. Registered on load so they cost nothing when AI is off. */

const en: Record<string, string> = {
  "ai.title": "AI Copilot",
  "ai.subtitle": "off by default · your key, your endpoint, your machine",
  "ai.enable": "Enable AI features",
  "ai.enableHint":
    "Adds a ✨ button to the toolbar. Nothing leaves this device until you run an action and confirm what gets sent.",
  "ai.provider": "Provider",
  "ai.endpoint": "Endpoint",
  "ai.model": "Model",
  "ai.apiKey": "API key",
  "ai.keyHintSession": "Held in memory for this session only.",
  "ai.keyHintLocal": "Local endpoints usually need no key.",
  "ai.persist": "Remember the key in this browser",
  "ai.persistWarn":
    "Saved as plaintext in localStorage — anything running in this browser can read it. Avoid on shared machines.",
  "ai.badgeLocal": "on this machine",
  "ai.badgeCloud": "cloud",
  "ai.context": "Context sent",
  "ai.ctx.selection": "Selection only",
  "ai.ctx.block": "Selection + surrounding block (recommended)",
  "ai.ctx.document": "Whole document",
  "ai.clearKey": "Forget key",
  "ai.viewLog": "Audit log",
  "ai.actions": "Actions",
  "ai.save": "Save",
  "ai.cancel": "Cancel",
  "ai.close": "Close",

  "ai.act.polish": "Polish",
  "ai.act.polishHint": "Grammar and flow, markdown and facts untouched",
  "ai.act.concise": "Make concise",
  "ai.act.conciseHint": "Same meaning, fewer words",
  "ai.act.expand": "Expand",
  "ai.act.expandHint": "Develop the point with more detail",
  "ai.act.continue": "Continue writing",
  "ai.act.continueHint": "Draft what plausibly comes next",
  "ai.act.translate": "Translate",
  "ai.act.translateHint": "Between English and Chinese, structure preserved",
  "ai.act.summarize": "Summarize",
  "ai.act.summarizeHint": "3–5 bullets, inserted as a suggestion",
  "ai.act.review": "Review",
  "ai.act.reviewHint": "Comments only — never edits your text",

  "ai.preview.title": "Review before sending",
  "ai.preview.meta": "{0} · {1}",
  "ai.preview.size": "{0} characters ≈ {1} tokens",
  "ai.preview.body": "Exactly this text will be sent:",
  "ai.preview.send": "Send",
  "ai.preview.skip": "Don't ask again this session",
  "ai.preview.wholeDoc": "This sends your entire document.",

  "ai.scan.title": "Possible secrets in this text",
  "ai.scan.body": "Found {0} — sending would disclose them to {1}.",
  "ai.scan.redacted": "Send redacted",
  "ai.scan.anyway": "Send anyway",

  "ai.diff.title": "AI suggestion",
  "ai.diff.stats": "{0} lines added · {1} removed · {2} rewritten",
  "ai.diff.acceptAll": "Accept all",
  "ai.diff.rejectAll": "Reject all",
  "ai.diff.apply": "Apply {0}",
  "ai.diff.none": "The model returned no changes.",
  "ai.diff.hunk": "Change {0}",

  "ai.review.title": "Review notes",
  "ai.review.hint": "Comments only — nothing in your document was changed.",

  "ai.log.title": "AI audit log",
  "ai.log.empty": "No calls yet.",
  "ai.log.clear": "Clear log",
  "ai.log.row": "{0} · {1} · {2} · in {3} / out {4} tokens · {5}",

  "ai.toast.disabled": "AI is off — turn it on in Settings → AI",
  "ai.toast.noKey": "Add an API key first",
  "ai.toast.nothing": "Nothing to work on",
  "ai.toast.running": "{0}… (Esc cancels)",
  "ai.toast.cancelled": "Cancelled",
  "ai.toast.failed": "AI failed: {0}",
  "ai.toast.applied": "Applied {0} change(s) — Ctrl+Z to undo",
  "ai.toast.discarded": "Suggestion discarded",
  "ai.toast.saved": "AI settings saved",
  "ai.toast.keyForgotten": "Key forgotten",
};

const zhCN: Record<string, string> = {
  "ai.title": "AI 副驾",
  "ai.subtitle": "默认关闭 · 自带 key、自选端点、可全程本机",
  "ai.enable": "启用 AI 功能",
  "ai.enableHint":
    "启用后工具栏出现 ✨ 按钮。在你执行动作并确认发送内容之前，不会有任何数据离开本机。",
  "ai.provider": "服务商",
  "ai.endpoint": "端点地址",
  "ai.model": "模型",
  "ai.apiKey": "API Key",
  "ai.keyHintSession": "仅保存在内存中，关闭页面即失效。",
  "ai.keyHintLocal": "本机端点通常不需要 key。",
  "ai.persist": "在此浏览器中记住 key",
  "ai.persistWarn":
    "会以明文存入 localStorage，本浏览器里运行的任何代码都能读到。公用电脑请勿勾选。",
  "ai.badgeLocal": "本机",
  "ai.badgeCloud": "云端",
  "ai.context": "发送的上下文",
  "ai.ctx.selection": "仅选中部分",
  "ai.ctx.block": "选区 + 相邻段落（推荐）",
  "ai.ctx.document": "整篇文档",
  "ai.clearKey": "忘记 key",
  "ai.viewLog": "调用日志",
  "ai.actions": "动作",
  "ai.save": "保存",
  "ai.cancel": "取消",
  "ai.close": "关闭",

  "ai.act.polish": "润色",
  "ai.act.polishHint": "只改语法与流畅度，不动 markdown 与事实",
  "ai.act.concise": "精简",
  "ai.act.conciseHint": "意思不变，字数更少",
  "ai.act.expand": "扩写",
  "ai.act.expandHint": "把这一点展开讲细",
  "ai.act.continue": "续写",
  "ai.act.continueHint": "接着往下写一段",
  "ai.act.translate": "翻译",
  "ai.act.translateHint": "中英互译，保留 markdown 结构",
  "ai.act.summarize": "摘要",
  "ai.act.summarizeHint": "3–5 条要点，以建议形式插入",
  "ai.act.review": "审阅",
  "ai.act.reviewHint": "只给批注，绝不改你的正文",

  "ai.preview.title": "发送前确认",
  "ai.preview.meta": "{0} · {1}",
  "ai.preview.size": "{0} 个字符 ≈ {1} tokens",
  "ai.preview.body": "将要发送的就是以下内容：",
  "ai.preview.send": "发送",
  "ai.preview.skip": "本次会话不再确认",
  "ai.preview.wholeDoc": "这会发送你的整篇文档。",

  "ai.scan.title": "检测到可能的敏感信息",
  "ai.scan.body": "发现 {0}；发送即会把它们暴露给 {1}。",
  "ai.scan.redacted": "脱敏后发送",
  "ai.scan.anyway": "仍然发送",

  "ai.diff.title": "AI 建议",
  "ai.diff.stats": "新增 {0} 行 · 删除 {1} 行 · 改写 {2} 处",
  "ai.diff.acceptAll": "全部接受",
  "ai.diff.rejectAll": "全部拒绝",
  "ai.diff.apply": "应用 {0}",
  "ai.diff.none": "模型没有提出任何修改。",
  "ai.diff.hunk": "修改 {0}",

  "ai.review.title": "审阅批注",
  "ai.review.hint": "只是批注 —— 你的文档没有被改动。",

  "ai.log.title": "AI 调用日志",
  "ai.log.empty": "还没有调用记录。",
  "ai.log.clear": "清空日志",
  "ai.log.row": "{0} · {1} · {2} · 输入 {3} / 输出 {4} tokens · {5}",

  "ai.toast.disabled": "AI 已关闭 —— 在「设置 → AI」中开启",
  "ai.toast.noKey": "请先填入 API Key",
  "ai.toast.nothing": "没有可处理的文本",
  "ai.toast.running": "{0}…（按 Esc 取消）",
  "ai.toast.cancelled": "已取消",
  "ai.toast.failed": "AI 出错：{0}",
  "ai.toast.applied": "已应用 {0} 处修改 —— Ctrl+Z 可撤销",
  "ai.toast.discarded": "已丢弃建议",
  "ai.toast.saved": "AI 设置已保存",
  "ai.toast.keyForgotten": "已忘记 key",
};

const ja: Record<string, string> = {
  "ai.title": "AI コパイロット",
  "ai.subtitle": "既定でオフ · 自分の鍵・自分のエンドポイント",
  "ai.enable": "AI 機能を有効にする",
  "ai.enableHint":
    "ツールバーに ✨ が表示されます。操作を実行して送信内容を確認するまで、データは端末から出ません。",
  "ai.provider": "プロバイダ",
  "ai.endpoint": "エンドポイント",
  "ai.model": "モデル",
  "ai.apiKey": "API キー",
  "ai.keyHintSession": "このセッションのメモリ上にのみ保持されます。",
  "ai.keyHintLocal": "ローカルのエンドポイントでは通常キーは不要です。",
  "ai.persist": "このブラウザにキーを保存する",
  "ai.persistWarn":
    "localStorage に平文で保存されます。共有端末では避けてください。",
  "ai.badgeLocal": "この端末",
  "ai.badgeCloud": "クラウド",
  "ai.context": "送信するコンテキスト",
  "ai.ctx.selection": "選択範囲のみ",
  "ai.ctx.block": "選択範囲 + 前後の段落（推奨）",
  "ai.ctx.document": "文書全体",
  "ai.clearKey": "キーを破棄",
  "ai.viewLog": "監査ログ",
  "ai.actions": "アクション",
  "ai.save": "保存",
  "ai.cancel": "キャンセル",
  "ai.close": "閉じる",

  "ai.act.polish": "推敲",
  "ai.act.polishHint": "文法と流れのみ。markdown と事実は変更しません",
  "ai.act.concise": "簡潔にする",
  "ai.act.conciseHint": "意味は同じで語数を減らす",
  "ai.act.expand": "詳しく書く",
  "ai.act.expandHint": "要点を掘り下げる",
  "ai.act.continue": "続きを書く",
  "ai.act.continueHint": "次に来る内容を下書きする",
  "ai.act.translate": "翻訳",
  "ai.act.translateHint": "英語と中国語の間で、構造を保持",
  "ai.act.summarize": "要約",
  "ai.act.summarizeHint": "3〜5 個の箇条書きを提案として挿入",
  "ai.act.review": "レビュー",
  "ai.act.reviewHint": "コメントのみ — 本文は変更しません",

  "ai.preview.title": "送信前の確認",
  "ai.preview.meta": "{0} · {1}",
  "ai.preview.size": "{0} 文字 ≈ {1} トークン",
  "ai.preview.body": "送信されるのは次の内容だけです：",
  "ai.preview.send": "送信",
  "ai.preview.skip": "このセッションでは確認しない",
  "ai.preview.wholeDoc": "文書全体が送信されます。",

  "ai.scan.title": "秘密情報の可能性",
  "ai.scan.body": "{0} 件検出しました。送信すると {1} に開示されます。",
  "ai.scan.redacted": "マスクして送信",
  "ai.scan.anyway": "それでも送信",

  "ai.diff.title": "AI の提案",
  "ai.diff.stats": "追加 {0} 行 · 削除 {1} 行 · 書き換え {2} 箇所",
  "ai.diff.acceptAll": "すべて採用",
  "ai.diff.rejectAll": "すべて却下",
  "ai.diff.apply": "{0} を適用",
  "ai.diff.none": "変更の提案はありませんでした。",
  "ai.diff.hunk": "変更 {0}",

  "ai.review.title": "レビューコメント",
  "ai.review.hint": "コメントのみ — 文書は変更されていません。",

  "ai.log.title": "AI 監査ログ",
  "ai.log.empty": "まだ呼び出しはありません。",
  "ai.log.clear": "ログを消去",
  "ai.log.row": "{0} · {1} · {2} · 入力 {3} / 出力 {4} トークン · {5}",

  "ai.toast.disabled": "AI はオフです — 設定 → AI で有効化してください",
  "ai.toast.noKey": "先に API キーを入力してください",
  "ai.toast.nothing": "対象のテキストがありません",
  "ai.toast.running": "{0}…（Esc で中止）",
  "ai.toast.cancelled": "中止しました",
  "ai.toast.failed": "AI エラー: {0}",
  "ai.toast.applied": "{0} 件を適用 — Ctrl+Z で元に戻せます",
  "ai.toast.discarded": "提案を破棄しました",
  "ai.toast.saved": "AI 設定を保存しました",
  "ai.toast.keyForgotten": "キーを破棄しました",
};

addMessages({ en, "zh-CN": zhCN, ja });


